# Make an initial guess using a hexagonal grid with s=5 and t=1 parameters as
# described by Ahrens & Beylkin. Then do a series of grid optimizations, each
# time using the result of the last calculation as initial guess:
#
# - First optimize the points & weights of this grid for to minimize the
#   residual for the monomials of degree l <= 4 ('[4,..]').
# - Then keep on increasing l by +1 (step:+1) until we find the first l for
#   which the optimized grid DOES NOT integrate the monomials of degree l
#   exactly (in this case (the hex{5;1}-grid) this will be lfinal=30).
# - Afterwards, optimize the grid for lfinal-1 ('..,-1]') (which is 29 in this
#   case), using the converged, but non-exact solution for lfinal as starting
#   guess. The resulting grid will be exact for order 29 again, but will in this
#   case possibly show a somewhat better weight distribution
{ point-group: icosahedral;
  degree: [4,step:+1,-1];
  max-step: 1e4*residual;
  initial-points: hex-grid{5;1;01c}
}
