# as 1-incremenal-search-up, but now search incrementally in DOWNWARD direction.
# The first grid optimized will be of degree l=35. Then we decrease l by 1
# (step:-1) until we find the first grid which integrates exactly.
#
# additionally, this config shows more fine-tuning options for the step size: by
# default use a maximum step size of 10^4 times the current residual, but never
# restrict the step size to maximum steps smaller than min:1e-9, and never allow
# steps larger than 7e-4.
#
# In this case, this finds the same grid as the final result of the
# 1-incremental-search-up.ini, but this may different in other cases.
{ point-group: icosahedral;
  degree: [35,step:-1];
  max-step: {1e4*residual; max:7e-4; min:1e-9};
  initial-points: hex-grid{5;1;01c}
}
