# This time do the following:
# - Read the initial cartesian points from a data file (e.g., a
#   set of points made by previous runs of the grid optimization).
#   The file here is called points 'inputs/312-guess.txt' (where
#   'inputs' is the directory relative to the current directory).
#
#   Regarding the file format, the following conventions hold:
#     * The first line of the file is ignored.
#     * Of every other line, the first three elements separated by spaces
#       are read as cartesian coordinates. The rest of the line is ignored
#       (including possible weights, if given)
#     * File reading ends once we encounter a line which cannot be read
#       as three floating point numbers.
#     * Lines startig with '#' or '//' are ignored.
# - Then optimize a grid of degree 30 with these starting points, and
#   use its result as initial guess for an optimization of degree 29.
{ point-group: icosahedral;
  degree: [30,29];
  max-step: {1e4*residual; max:7e-4; min:1e-9};
  initial-points: read-cartesian{inputs/points-312-guess.txt}
}
