# as 3-refine-initial grid, but this time read the input positions as
# barycentric coordinates of the fundamental region (for icosahedral,
# tetrahedral, and octahedral grids this is a triangle in all cases). The inputs
# is given in triples of tau0, tau1, tauC. What these mean depends on the point
# group (see ConvertBarycentricToCartesian function).
#
# For icosahedral grids, both tau0 and tau1 refer to vertices of the
# icosahedron, and tauC refers to the mid point ('c'entral point) of an
# icosahedron face.
#
# The file format works as in the cartesian case: The first line is ignored, and
# only the first three scalars are read as actual input. Reading stops once we
# reach a line which does not start with three scalars.
{ point-group: icosahedral;
  degree: [step:+1,-1];
  max-step: 1e-3;
  initial-points: read-barycentric{inputs/barycentric-guess.txt}
}
