# This does the same as 1-incremental-search-up.ini, except for using offsets on
# the m and n coordinates for the hexagonal initial grid (see Ahrens & Beylkin).
# With non-zero offsets, or an order different from 01c, we will get rules which
# do not necessarily include the icosahedral vertex v0 (the orbit of length 12).
# Not sure if we want any of those -- needs trying.
# These kinds of rules also tend to get stuck in two alternating fixed points.
# could be fixed by DIIS... but have not built that into the program yet.
{ point-group: icosahedral;
  degree: [step:+1,-1];
  max-step: {1e2*residual; max:1e-3};
  max-iter: 400;
  initial-points: hex-grid{3;0;01c;0.5;-0.5}
}
