# This file contains a command to export the final integration points to a data
# file. With 'points:all', all symmetry-equivalent points will be explicitly
# generated and exported (e.g., here, a general seed point leads to 60 exported
# points, a seed point on a vertex leads to 12 exported points, etc).
# Alternatively, one can give 'points:seeds', in which case only the unique
# points are exported.
#
# If the required python packages are installed and a suitable graphics card
# driver is present, the so-computed grid points can be visualized with
#
#     python visualize_rule.py ico-3-2.dat
#
# (use filename you used for export, here 'ico-3-2.dat')
{ point-group: icosahedral;
  degree: [15,step:+1,-1];
  max-step: 1e4*residual;
  initial-points: hex-grid{3;2;01c};
  export: {file: ico-3-2.dat; format: text; points: seeds}
}
