/// @file CxIterTools.h Iteration-sequence generation/transformation (note: used
/// to also contain C++ template/parameter pack meta-programming primitives,
/// which are now in `CxMetaLight.h` and `CxMeta.h`)
///
/// # Number/vector/point sequence generators
///
/// - Number sequence generators (typically for integers):
///   The following functions return lightweight meta-sequence objects
///   which generate the associated number sequence $S$ if iterated over:
///
///    | Sequence Generator             | Generated Sequence                   | Notes
///    |:-------------------------------|--------------------------------------|-----------------------
///    |   `auto numbers()      `       | $S := [0, 1, 2, ...]$                | infinite sequence
///    |   `auto numbers_from(b)`       | $S := [b, b + 1, b + 2, ...]$        | infinite sequence
///    |   `auto xrange(e)      `       | $S := [0, 1, 2, ..., e)$             | semi-open, e ∉ S
///    |   `auto irange(e)      `       | $S := [0, 1, 2, ..., e]$             | closed, includes e ∈ S
///    |   `auto xrange(b,e)    `       | $S := [b, b + 1, b + 2, ..., e)$     | semi-open, e ∉ S
///    |   `auto irange(b,e)    `       | $S := [b, b + 1, b + 2, ..., e]$     | closed, includes e ∈ S
///    |   `auto xrange(b,e,s)  `       | $S := [b, b + s, b + 2*s, ..., e)$   | semi-open, e ∉ S
///    |   `auto irange(b,e,s)  `       | $S := [b, b + s, b + 2*s, ..., e]$   | closed, includes e ∈ S
///
///   + The functions have one template argument `template <class scalar_t>`. `scalar_t` defines
///     the types of `e` (end/last), `b` (begin/first), and `s` (step), as well as the
///     output type of the meta-sequence iterators.
///
///   + Warnings:
///
///     - `numbers()` and `numbers_from(b)`: For finite integer types, the
///       sequences generated by will eventually wrap around. Use integer
///       types which are large enough to contain your target number range! Be
///       especially careful about ranges derived from literal types. E.g.,
///       ```
///           // iterates over `int`s only (often only 32bit!)
///           for (auto i : cx::iter::numbers_from(0)) { ... }
///
///           // iterates over `unsigned long long` numbers
///           for (auto i : cx::iter::numbers_from(0ull)) { ... }
///       ```
///     - `e` versus `s`: Atm, the meta-sequence iterators will check the end condition using a
///       test amounting to `*it == e`; that is, they check for *exact* equality. If the sequence
///       generated by your combination of `b` and `s` does not actually include `e`, or if you
///       use types and `b`/`e` values which induce inexact arithmetic (e.g., `float`/`double`
///       types and `b`,`e`, or `s` which cannot be exactly represented as binary floats), then
///       the meta-sequence will never meet its end condition.
///
///       E.g., `cx::iter::irange(0., 1., 0.1)` will not terminate on most platforms, because
///       `b`,`e`,`s` are all `double` literals, and `0.1` cannot be exactly represented in terms
///       of the IEEE binary64 floats which `double` typically maps to.
///
///   + Example:
///     ```
///         std::vector<char const *> vec{"aa", "bb", "cc", "dd"};
///         for (auto i : cx::iter::xrange(vec.size())) {
///            std::cout << "vec[" << i << "] = '" << vec[i] << "'\n";
///         }
///     ```
///     Output:
///     ``` output
///         [0] 'aa'
///         [1] 'aa'
///         [2] 'aa'
///         [3] 'aa'
///     ```
/// - Vector sequence generators / point sequence generators:
///
///   + `ray_grid(vfrom, vto, N, trafo = _Identity<>)`:
///     Return meta-sequence for a equidistant `N`-point grid along the ray
///
///     \f[ v(t) = (1 - t) v_\mathrm{from} + t v_\mathrm{to} \f]
///
///     which is subsequently mapped through the function `trafo`, if provided.
///     `N` must be >= 2, and `vfrom` and `vend` are both included.
///
/// # Meta-sequences for iteration
///
/// - `reversed(seq)`:
///    For a sequence with bidirectional iterators, return a meta-sequence which iterates
///    it in reverse.
///
/// - `cycle(seq)`:
///    Return a meta-sequence which cycles through an input sequence ad inifitum
///
/// - `repeat<FElement>(element, N)`:
///    Return a meta-sequence consisting of `N` repetitions of `element`
///
/// - `repeat<FElement>(element)`:
///    Return a meta-sequence `[e,e,e,...]` infinitely repeating e := `element`
///
/// - `mapv<FSequence, FTrafo>(seq, trafo)`:
///    `mapv(seq, trafo)` returns a meta-sequence corresponding to
///    `[trafo(e) for e in seq]`; that is, which maps the original sequence
///    elements through the function `trafo` on iterator dereferencing.
///
/// - `mapiv<FSequence, FTrafo>(seq, trafo)`:
///    `mapiv(seq, trafo)` returns a meta-sequence corresponding to
///    `[trafo(i,e) for (i,e) in enumerate(seq)]`; that is, which maps elements `seq[i]`
///    through `trafo(i, seq[i])` on iterator dereferencing.
///
/// - `deref(seq)`:
///    `deref(seq)` returns a meta-sequence which is equivalent to seq, except
///    that dereferencing its iterators returns operator* applied to the
///    original seq elements (`[*e for e in seq]`), rather than just the original
///    elements (`[e for e in seq]`) themselves.
///
///    This can be useful for handling sequences of pointers, smart-pointers, or
///    otherwise wrapped objects.
///
///    - see also: `template<class FBaseIt, unsigned N> using deref_iterator_t = ...;`
///
/// - `sorted(seq)`
///
/// - `sorted<FSequence, FSortKey>(seq, key)`
///
/// - `zip(seqs...)`:
///   `zip(A,B,C,...)` returns a meta-sequence over tuples with matching items
///   from `A`, `B`, `C`, ...:
///
///       zip(A,B,...) ≍ [tuple(A[i], B[i], ...) for i in range(min(len(A), len(B), ...)].
///
///   + WARNING: if reversed() is meant to be used with `zip()`, then all input sequences
///     must have the same length to yield correct results!
///   + Otherwise `zip(A,B,C,...)` will terminate on the shortest input sequence.
///
/// - `enumerate(seq)`
///
/// - `reversible_enumerate(seq)`:
///    As enumerate(seq), but returns a meta-sequence which can be subjected to `reversed()`.
///
/// TODO:
/// - Split off light-weight and heavy-weight meta-programming stuff (CxMetaLight.h, CxMetaFull.h)
/// - Split off light-weight and heavy-weight iter tools
/// - Consider removing support for `CX_ENUMERATE_IAV != 0`
#ifndef CX_ITER_TOOLS_H
#define CX_ITER_TOOLS_H

#include "CxMetaLight.h"
#include <iterator> // for defining iterator categories: https://en.cppreference.com/w/cpp/iterator/iterator_tags
#include <tuple> // for zip (uses std::tie)
#include <utility>
#include <list>  // for result type of sorted()
#include <stdexcept>
#ifndef assert
   #include <cassert>
#endif

#if !defined(CX_ENUMERATE_IAV)
   // 0: make enumerate return a trivial 'index and value' *iterator result:, just a
   //       struct iav_t { index_type i; value_type &v; };
   // 1: use TIndexAndValue with extra operators an stuff, as below.
   #define CX_ENUMERATE_IAV 0
#endif

// namespace for the sequence transformations:
//
//    reversed(),
//    sorted() product(), combinations(), permutations(),
//    ...
#define _CxIter cx::iter
#define _Namespace_CxIter_Begin namespace cx { namespace iter
#define _Namespace_CxIter_End }


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ▒▒ NEXT: Iteration tools for sequence generation; the following take some
// ▒▒       numeric or vector-valued arguments, and generate output sequences
// ▒▒       of numbers/vectors/function values.
// ▒▒
// ▒▒       - Number sequence generators:
// ▒▒
// ▒▒         | Sequence Generator             | Generated Sequence                   | Notes
// ▒▒         |:-------------------------------|--------------------------------------|-----------------------
// ▒▒         |   `auto numbers()      `       | $S := [0, 1, 2, ...]$                | infinite sequence
// ▒▒         |   `auto numbers_from(b)`       | $S := [b, b + 1, b + 2, ...]$        | infinite sequence
// ▒▒         |   `auto xrange(e)      `       | $S := [0, 1, 2, ..., e)$             | semi-open, e ∉ S
// ▒▒         |   `auto irange(e)      `       | $S := [0, 1, 2, ..., e]$             | closed, includes e ∈ S
// ▒▒         |   `auto xrange(b,e)    `       | $S := [b, b + 1, b + 2, ..., e)$     | semi-open, e ∉ S
// ▒▒         |   `auto irange(b,e)    `       | $S := [b, b + 1, b + 2, ..., e]$     | closed, includes e ∈ S
// ▒▒         |   `auto xrange(b,e,s)  `       | $S := [b, b + s, b + 2*s, ..., e)$   | semi-open, e ∉ S
// ▒▒         |   `auto irange(b,e,s)  `       | $S := [b, b + s, b + 2*s, ..., e]$   | closed, includes e ∈ S
// ▒▒
// ▒▒       - Vector/point sequence generators:
// ▒▒
// ▒▒         + `ray_grid(vfrom, vto, N, trafo = _Identity<>)`
// ▒▒
// ──────────────────────────────────────────────────────────────────────────



// formal iterator interface stuff
#define CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(value_xref_t) \
      using value_type = _CxMeta::without_ref_t<value_xref_t>; \
      using difference_type = std::ptrdiff_t; \
      using reference = value_type&; \
      using pointer = value_type*; \
      using iterator_category = std::bidirectional_iterator_tag; \
      iterator operator ++(int) noexcept { iterator it{*this}; this->operator ++(); return it; } \
      iterator operator --(int) noexcept { iterator it{*this}; this->operator --(); return it; } \
      bool operator ==(iterator const &other) const noexcept { return !this->operator !=(other); } \
      auto operator->() noexcept -> wrap_as_ptr_t<value_xref_t> { return wrap_as_ptr(this->operator*()); }
_Namespace_CxIter_Begin {
} _Namespace_CxIter_End


#ifdef INCLUDE_ABANDONED
// _Namespace_CxIter_Begin {
//    /// `wrap_as_ptr_t<T>`: Wrapper with a pointer-like interface for concrete
//    /// values and references:
//    ///
//    /// - if T is NOT a reference type, `wrap_as_ptr_t<T> p{t}` stores a copy
//    ///   of `t`, and `*p` and `p->` refer to the elements of this stored copy.
//    ///
//    /// - if T is a reference type, `wrap_as_ptr_t<T> p{t}` stores a pointer
//    ///   to the existing T object `t`, and `*p` and `p->` refer to the
//    ///   external `t` object.
//    ///
//    /// This serves two purposes:
//    /// - `wrap_as_ptr_t<value_type>` can be used as generic return type for the
//    ///   operator ->() implementations of generic sequence tranform
//    ///   iterators, even if the iterators of the input sequence return by
//    ///   value (e.g., comes out of an generator, like `iter::numbers()`) and
//    ///   cannot have their addresses taken of.
//    ///
//    /// - `wrap_as_ptr_t<value_type>` is both copyable, movable, and assignable,
//    ///   and can therefore be put into std containers (unlike value_types of
//    ///   reference character).
//    template<class T, class = void>
//    struct wrap_as_ptr_t;
//    //      ^- name ideas: valref_to_ptr_t? ptr_wrap_t? wrap_as_ptr_t? pseudo_ptr_t? value_ptr_wrap_t? value_ptr_t? ptr_like_value_t?
//
//    template<class T>
//    struct wrap_as_ptr_t<T, void_if_t<!std::is_reference<T>::value> > {
//       using this_type = wrap_as_ptr_t;
//       using value_type = T;
//       value_type m_value;
//
//       value_type const &operator*() const { return m_value; }
//       value_type const *operator->() const { return &m_value; }
//       value_type &operator*() { return m_value; }
//       value_type *operator->() { return &m_value; }
//       bool operator < (this_type const &other) const { return m_value < other.m_value; }
//
//       explicit wrap_as_ptr_t(value_type &&pv) : m_value{std::move(pv)} {}
//       explicit wrap_as_ptr_t(value_type const &pv) : m_value{pv} {}
// //          operator value_type const&() const { return m_value; }
//    };
//
//    template<class T>
//    struct wrap_as_ptr_t<T, void_if_t<std::is_reference<T>::value> > {
//       using value_type = typename std::remove_reference<T>::type;
//       using this_type = wrap_as_ptr_t;
//       value_type *m_ptr;
//
//       value_type &operator*() { return *m_ptr; }
//       value_type *operator->() { return m_ptr; }
//       value_type const &operator*() const { return *m_ptr; }
//       value_type const *operator->() const { return m_ptr; }
//       bool operator < (this_type const &other) const { return *m_ptr < *other.m_ptr; }
//
//       explicit wrap_as_ptr_t(value_type &pv) : m_ptr{&pv} {}
// //       operator value_type const&() const { return m_ptr; }
//    };
//
//    namespace iter_detail {
//       template<class T>
//       using FValueOrRef = wrap_as_ptr_t<T, void>;
//    } // namespace iter_detail
//
// } _Namespace_CxIter_End
#endif // INCLUDE_ABANDONED

_Namespace_CxIter_Begin {
   template<class T>
   struct ptr_wrapped_value_t {
      // = wrap_as_ptr_t<T> if T is *not* a reference type, see below
      using this_type = ptr_wrapped_value_t;
      using value_type = T;
      value_type m_value;

      value_type const &operator*() const { return m_value; }
      value_type const *operator->() const { return &m_value; }
      value_type &operator*() { return m_value; }
      value_type *operator->() { return &m_value; }
      bool operator < (this_type const &other) const { return m_value < other.m_value; }

      explicit ptr_wrapped_value_t(value_type &&pv) noexcept : m_value{std::move(pv)} {}
      explicit ptr_wrapped_value_t(value_type const &pv) noexcept : m_value{pv} {}
//          operator value_type const&() const { return m_value; }
   };

   template<class T>
   struct ptr_wrapped_ref_t {
      // = wrap_as_ptr_t<T> if T *is* a reference type, see below
      using value_type = typename std::remove_reference<T>::type;
      using this_type = ptr_wrapped_ref_t;
      value_type *m_ptr;

      value_type &operator*() { return *m_ptr; }
      value_type *operator->() { return m_ptr; }
      value_type const &operator*() const { return *m_ptr; }
      value_type const *operator->() const { return m_ptr; }
      bool operator < (this_type const &other) const { return *m_ptr < *other.m_ptr; }

      explicit ptr_wrapped_ref_t(value_type &pv) noexcept : m_ptr{&pv} {}
//       operator value_type const&() const { return m_ptr; }
   };

   /// `wrap_as_ptr_t<T>`: Wrapper with a pointer-like interface for concrete
   /// values and references:
   ///
   /// - if T is NOT a reference type, `wrap_as_ptr_t<T> p{t}` stores a copy
   ///   of `t`, and `*p` and `p->` refer to the elements of this stored copy.
   ///
   /// - if T is a reference type, `wrap_as_ptr_t<T> p{t}` stores a pointer
   ///   to the existing T object `t`, and `*p` and `p->` refer to the
   ///   external `t` object.
   ///
   /// This serves two purposes:
   /// - `wrap_as_ptr_t<value_type>` can be used as generic return type for the
   ///   operator ->() implementations of generic sequence tranform
   ///   iterators, even if the iterators of the input sequence return by
   ///   value (e.g., comes out of an generator, like `iter::numbers()`) and
   ///   cannot have their addresses taken of.
   ///
   /// - `wrap_as_ptr_t<value_type>` is both copyable, movable, and assignable,
   ///   and can therefore be put into std containers (unlike value_types of
   ///   reference character).
   template<class T>
   using wrap_as_ptr_t
      = typename std::conditional<
            std::is_reference<T>::value,
            ptr_wrapped_ref_t<T>,
            ptr_wrapped_value_t<T>
         >::type;
   //      ^- name ideas: valref_to_ptr_t? ptr_wrap_t? wrap_as_ptr_t?
   //         pseudo_ptr_t? value_ptr_wrap_t? value_ptr_t? ptr_like_value_t?
   //
   // ^-- would be nice if we could replace the ptr_wrapped_ref_t<T>
   //     branch of the std::conditional with just T*. But I'd need
   //     to find a way of how to construct those things in that case,
   //     as T* has no T& constructor, of course...
   //     Also, the sorting operator wouldn't work anymore, but I do not think
   //     this is still used anyway.

   template<class T> auto wrap_as_ptr(T &&t) -> wrap_as_ptr_t<T> { return wrap_as_ptr_t<T>{std::forward<T>(t)}; }


   namespace iter_detail {
      template<class T> using FValueOrRef = wrap_as_ptr_t<T>;
   } // namespace iter_detail

} _Namespace_CxIter_End


_Namespace_CxIter_Begin {
   using flagfield_t = unsigned;

   bool constexpr _FlagOnQ(flagfield_t bpat, flagfield_t test) { return bool(bpat & test); }
   bool constexpr _FlagOffQ(flagfield_t bpat, flagfield_t test) { return !bool(bpat & test); }

   /// Returns 1 if flag `test` is set in bpat, otherwise 0.
   unsigned constexpr _FlagValQ(flagfield_t bpat, unsigned test) { return bool(bpat & test)? 1u : 0u; }

   namespace range_detail {
      enum {
         RANGE_NeverEnds = 0x01,
         RANGE_IncludeEnd = 0x02
      };

      template<class scalar_t, flagfield_t _Flags = 0>
      struct _TNumericRangeGenerator_BES { // BES: begin, end, step
         scalar_t m_begin, m_end, m_step;
         struct iterator {
            scalar_t i;
            _TNumericRangeGenerator_BES const *pNr;
            bool constexpr operator != (iterator const &other) const {
               return (this->i != other.i);
            }
//             bool constexpr operator == (iterator const &other) const { return !this->operator != (other); }
            iterator &operator ++() { i += pNr->m_step; return *this; }
            iterator &operator --() { i -= pNr->m_step; return *this; }
            scalar_t operator *() const { return i; }
//             scalar_t const *operator ->() const { return &i; }

            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(scalar_t)
         };
         iterator begin() const { return iterator{m_begin, this}; }
         iterator end() const { return iterator{(_FlagOffQ(_Flags, RANGE_IncludeEnd)? m_end : m_end + m_step), this}; }
         template<class _Op> void for_all(_Op op) const { for (iterator it = begin(); it != end(); ++it) { op(*it); }; }
      };

      template<class scalar_t, flagfield_t _Flags = 0>
      struct _TNumericRangeGenerator_BE { // BES: begin, end
         scalar_t m_begin, m_end;
         struct iterator {
            scalar_t i;
            bool constexpr operator != (iterator const &other) const {
               return _FlagOnQ(_Flags, RANGE_NeverEnds)? true : (this->i != other.i);
            }
//             bool constexpr operator == (iterator const &other) const { return !this->operator != (other); }
            iterator &operator ++() { ++i; return *this; }
            iterator &operator --() { --i; return *this; }
            scalar_t operator *() const { return i; }
//             scalar_t const *operator ->() const { return &i; }

            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(scalar_t)
         };
         iterator begin() const { return iterator{m_begin}; }
         iterator end() const { return iterator{m_end}; }
         size_t size() const { return (m_begin < m_end)? size_t(m_end - m_begin) : 0u; }
         template<class _Op> void for_all(_Op op) const { for (iterator it = begin(); it != end(); ++it) { op(*it); }; }
      };

   } // namespace iter_detail

   /// Generate infinite sequence [0, 1, 2, ..., ]
   template<class scalar_t> auto numbers()
   -> range_detail::_TNumericRangeGenerator_BE<scalar_t, range_detail::RANGE_NeverEnds> { return {0, 0}; }

   /// Generate infinite sequence [iFirst, iFirst + 1, iFirst + 2, ..., ]
   template<class scalar_t> auto numbers_from(scalar_t iFirst)
   -> range_detail::_TNumericRangeGenerator_BE<scalar_t, range_detail::RANGE_NeverEnds> { return {iFirst, 0}; }


   /// Generate sequence [0, 1, 2, ..., iLast),
   /// with iLast EXCLUSIVE (use count_to() for the inclusive version).
   template<class scalar_t> auto xrange(scalar_t iLast)
   -> range_detail::_TNumericRangeGenerator_BE<scalar_t> { return {0, iLast}; }

   /// Generate sequence [0, 1, 2, ..., iLast],
   /// with iLast INCLUSIVE (use count() for the inclusive version).
   template<class scalar_t> auto irange(scalar_t iLast)
   -> range_detail::_TNumericRangeGenerator_BE<scalar_t> { return {0, iLast + 1}; }


   /// Generate sequence [iFirst, iFirst + 1, iFirst + 2, ..., iLast),
   /// with iLast EXCLUSIVE (use count_to() for the inclusive version).
   template<class scalar_t> auto xrange(scalar_t iFirst, scalar_t iLast)
   -> range_detail::_TNumericRangeGenerator_BE<scalar_t> { return {iFirst, iLast}; }

   /// Generate sequence [iFirst, iFirst + 1, iFirst + 2, ..., iLast],
   /// with iLast INCLUSIVE (use count() for the inclusive version).
   template<class scalar_t> auto irange(scalar_t iFirst, scalar_t iLast)
   -> range_detail::_TNumericRangeGenerator_BE<scalar_t> { return {iFirst, iLast + 1}; }


   /// Generate sequence [iFirst, iFirst + iStep, iFirst + 2*iStep, ..., iLast),
   /// with iLast EXCLUSIVE (use count_to() for the inclusive version).
   template<class scalar_t> auto xrange(scalar_t iFirst, scalar_t iLast, scalar_t iStep)
   -> range_detail::_TNumericRangeGenerator_BES<scalar_t, range_detail::RANGE_IncludeEnd> { return {iFirst, iLast, iStep}; }

   /// Generate sequence [iFirst, iFirst + iStep, iFirst + 2*iStep, ..., iLast],
   /// with iLast INCLUSIVE (use count() for the inclusive version).
   template<class scalar_t> auto irange(scalar_t iFirst, scalar_t iLast, scalar_t iStep)
   -> range_detail::_TNumericRangeGenerator_BES<scalar_t, range_detail::RANGE_IncludeEnd> { return {iFirst, iLast, iStep}; }

   // Not sure about naming:
   //    xrange + irange?
   //    num_range + num_range_incl?
   //    count + count_to?
   //    numbers + numbers_incl?
   //    interval_cc + interval_co?
   //    num_grid?
   //
   // WARNING: requires that the sequence includes iLast EXACTLY, otherwise
   // the iteration will be infinite.

   // soi = semi-open interval (does not include interval end point)
   // cli = closed interval (includes interval end point)


   namespace iter_detail {
      template<class vec_t, class _Trafo>
      struct _RayGridGenerator1 {
         vec_t m_from, m_to, m_step;
         size_t   m_ifirst, m_ilast;
         _Trafo   m_trafo;
         using value_type = decltype(std::declval<_Trafo>()(m_from));
         struct iterator {
            size_t i;
            _RayGridGenerator1 const *g;
            bool constexpr operator != (iterator const &other) const { return this->i != other.i; }
            void operator ++() { ++ i; }
            value_type operator *() const { return g->m_trafo(g->m_from + i * g->m_step); }
         };
         iterator begin() const { return iterator{m_ifirst, this}; }
         iterator end() const { return iterator{m_ilast, this}; }

         static _RayGridGenerator1 constexpr _Create(vec_t vfrom, vec_t vto, size_t ib, size_t ie, size_t N, _Trafo func = _Trafo()) {
            return {vfrom, vto, (vto - vfrom)/(N - 1u), ib, N - ie, func };
         };
      };
   }

   template<class _Out, class _In>
   struct _IdentityTrafo { _Out constexpr operator() (_In const &in) const { return in; } };

   /// Return generator sequence for a equidistant N-point grid along the ray
   ///
   ///   v(t) = (1-t)*vfrom + t*vto,
   ///
   /// which is subsequently mapped through the function func(), if provided.
   /// N must be >= 2, and vstart and vend are both included.
   template<unsigned _IncludeFrom=1, unsigned _IncludeTo=1, class vec_t, class _Trafo = _IdentityTrafo<vec_t, vec_t> >
   auto ray_grid(vec_t vfrom, vec_t vto, size_t N, _Trafo func = _Trafo())
   -> iter_detail::_RayGridGenerator1<vec_t, _Trafo> {
      return iter_detail::_RayGridGenerator1<vec_t, _Trafo>::_Create(
         vfrom, vto,
         (1u-_IncludeFrom), (1u-_IncludeTo), N + (1u-_IncludeFrom) + (1u-_IncludeTo),
   //       0u, 0u, N + 0u,
         func
      );
   }
   // ^-- FIXME: do I really want those _IncludeFrom / _IncludeTo versions?


} _Namespace_CxIter_End

#ifdef INCLUDE_OPTIONALS
// Note: ^-- previous version of _TNumericRangeGenerator_BES was constructed like this:
// ```
//     namespace range_detail {
//        template<class scalar_t = std::ptrdiff_t, bool _IncludeEnd = false>
//        struct _TNumericRangeGenerator_BES { // BES: begin, end, step
//           scalar_t m_start, m_end, m_step;
//           struct iterator {
//              scalar_t i;
//              _TNumericRangeGenerator_Bes const *pNr;
//              bool constexpr operator != (iterator const &other) const {
//                 return (_IncludeEnd?
//                    ((pNr->m_step >= 0)? (this->i <= other.i) : (other.i <= this->i)) :
//                    ((pNr->m_step >= 0)? (this->i < other.i) : (other.i < this->i))
//                 );
//                 // ^-- note 'less' compare! That's because for range-based for
//                 //     we only need the comparison with .end(). And we use `<=`
//                 //     instead of `<` to get the end points included.
//              }
//              iterator &operator ++() { i += pNr->m_step; return *this; }
//              iterator &operator --() { i -= pNr->m_step; return *this; }
//              scalar_t operator *() const { return i; }
//           };
//           iterator begin() const { return iterator{m_start, this}; }
//           iterator end() const { return iterator{m_end, this}; }
//        };
//     } // namespace range_detail
// ```
// This worked fine when used by itself and with numeric types; in particular,
// in that case it would also allow being used with floats and other inexact
// types rather safely (the current version of count(beg,end,step) will just
// iterate indefinitely unless one of the iterators in `for (auto it = beg; ; ++
// it)` agrees with it.i == end.i EXACTLY!). However, it would likely create
// problems if combined with the sequence transformations or other generators.
// So for this reason I leave the more conservative version for now.
#endif // INCLUDE_OPTIONALS



// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ▒▒ NEXT: Iteration tools for sequence transformations; all of the following
// ▒▒       take an input sequence (seq) and return an object representing a
// ▒▒       meta-sequence which can be:
// ▒▒       - (a) iterated over, such as in
// ▒▒         ```
// ▒▒             for ([ie,e] : cx::enumerate(seq)) {
// ▒▒                std::cout << "seq[" << ie << "] = " << e << std::endl;
// ▒▒             }
// ▒▒         ```
// ▒▒       - (b) invoked a function/functor/lambda on, as in
// ▒▒         ```
// ▒▒             cx::enumerate(seq).for_all([&](size_t ie, FSeq::value_type const &e) {
// ▒▒                std::cout << "seq[" << ie << "] = " << e << std::endl;
// ▒▒             }
// ▒▒         ```
// ▒▒       The sequence transformations are:
// ▒▒       - meta_seq::identity(seq): returns seq itself
// ▒▒       - enumerate(seq): for each e in seq, the meta sequence yields (ie,e), where
// ▒▒             ie is the index of the element:
// ▒▒             - ie = 0 for e = *seq.begin()
// ▒▒             - ie = 1 for e = *(++iterator(begin)),,
// ▒▒             - ie = 2 for e = *(++(++iterator(begin()))),
// ▒▒       - ...[FIXME: add]
// ──────────────────────────────────────────────────────────────────────────
//
// COMMENTS ON THE IMPLEMENTATION
// ------------------------------
// + Members & relations:
//   Fun fact: there is a large amount of stuff saying what kinds of
//   member types a iterator of a certain category is supposed to have.
//   E.g.: https://en.cppreference.com/w/cpp/iterator
//   (and e.g., `std::list<T>(beg,end)` refuses to work unless a bunch of
//   those typedefs are set, although it is unclear to me whether they are
//   actually used for anything)
//
//   However: what I could not find in >30min of looking is what those
//   typedefs are actually used for, and in which relation to the member
//   functions they are supposed to stand. E.g., in
//   TReversedSequenceWrapper<>::iterator, we're not returning `pointer` for
//   `operator ->`. Is that bad? No idea. I didn't see anything telling me
//   that I have to! Should probably still be revised at some point...
//
// + Most of the meta-sequence iterators will contain code which
//   references the original sequence's iterators as
//   ```
//       using std::begin;
//       template<class FSequence, ...>
//       class <TMetaSequence> {
//           using FBaseIt = decltype(begin(std::declval<FSequence>()))
//           ...
//       }
//   ```
//   — that is, as whatever `seq.begin()` of the original sequence returns.
//
// + Furthermore, the meta-sequence iterators will reference the return
//   type of original sequence's iterators like this:
//   ```
//       using input_type = decltype(*std::declval<FBaseIt>());
//   ```
//   If that is the case, note that `input_type` is defined as the decltype
//   of the *EXPRESSION* of whatever `*seq.begin()` of the original sequence
//   returns, *WITHOUT* reduction of reference or cv character!
//
//   That means that in most cases `input_type` (as well as its reflection in
//   the meta-sequence's `value_type`, if present) will be a *REFERENCE*!
//   That includes iteration over standard containers (e.g., `std::vector<>`)
//   as well as over raw arrays. It may not be a reference if the sequence we
//   iterate over is not in fact a container, but something which generates
//   and returns items by value (e.g., the result of `mapv` or `mapiv`).
_Namespace_CxIter_Begin {
   namespace iter_detail {
      enum {
         METASEQ_Reversible = 0x01,
         METASEQ_Mask = 0x0f
      };
   }
   using iter_detail::METASEQ_Reversible;
   using iter_detail::METASEQ_Mask;

   namespace iter_detail {
      // _begin/_end just defer to std::begin // std::end. Why define them? Well,
      // when we implement our own iterators, "using std::begin;" inside the
      // class can generate weird shadowing / "changes meaning of" errors.
      // E.g.:
      // ```
      //   error: declaration of
      ///   'constexpr cx::iter::iter_detail::TIndexedSequenceWrapper<FSequence, _Flags, _TIndexAndValue>::iterator cx::iter::iter_detail::TIndexedSequenceWrapper<FSequence, _Flags, _TIndexAndValue>::begin() const'
      //    changes meaning of 'begin' [-fpermissive]
      //    iterator constexpr begin() const noexcept { using std::begin; return iterator{0, begin(m_sequence)}; }
      // ```
      using std::begin;
      using std::end;
      template<typename T> constexpr auto _begin(T &t) -> decltype(begin(t)) { return begin(t); }
      template<typename T> constexpr auto _end(T &t) -> decltype(end(t)) { return end(t); }
   }


   namespace iter_detail {
      using std::begin;
      using std::end;
      template<class FSequence>
      struct TReversedSequenceWrapper {
         // The right way to iterate in reverse through a sequence is this:
         // ```
         //
         //     for (iterator it = seq.end(); it != seq.begin(); ) { -- it;
         //        // (do stuff here)
         //     }
         // ```
         // That works for signed integers, unsigned integers, pointers,
         // iterators, etc., has exactly the minimum number of arithmetic
         // operations (just the same as a forward iteration), and never
         // violates constraints like never forming an iterator to a invalid
         // element except to end() (which is allowed!).
         //
         // Unfortunately, this cannot be translated 1:1 to a range-based for
         // loop: there is no way to include code to be executed at the start of
         // the loop body (just another thing the C++ commitee did not think
         // through...). So we have little choice other than to either (a) store
         // a copy of the iterator, or a flag to indicate whether it already was
         // decremented (both super ugly and error-prone) or to decremet it on
         // each dereference, and hope that the compiler is able to figure it
         // out and merge the different decrement operations. For now we for for
         // the latter option.
         struct iterator {
            // using FSequenceIt = decltype(begin(std::declval<FSequence>()));
            using FSequenceIt = _SequenceIterT<FSequence>;
            using value_xref_t = decltype(*std::declval<FSequenceIt>());
            // ^-- note that this is "decltype", not "auto"!---it is whatever
            //     *it returns (often a reference!)

            FSequenceIt p; // original sequence iterator to element

            bool operator !=(iterator const &other) const noexcept { return this->p != other.p; }
            iterator &operator ++() noexcept { -- p; return *this; }
            iterator &operator --() noexcept { ++ p; return *this; }
            value_xref_t operator *() const noexcept { FSequenceIt pm1 = p; -- pm1; return *pm1; }

            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(value_xref_t)
         };
         FSequence m_sequence;
         iterator begin() const noexcept { using std::end; return iterator{end(m_sequence)}; }
         iterator end() const noexcept { using std::begin; return iterator{begin(m_sequence)}; }
         template<class _Op> void for_all(_Op op) const { for (iterator it = begin(); it != end(); ++it) { op(*it); }; }
         std::size_t constexpr size() const noexcept { return _SequenceSize(m_sequence); }
      };
   } // namespace iter_detail

   // For a sequence with bidirectional iterators, return a meta-object which iterates
   // it in reverse. This should neither copy the sequence, not any of the values
   template<class FSequence>
   auto constexpr reversed(FSequence &&sequence) noexcept -> iter_detail::TReversedSequenceWrapper<FSequence> {
      return {std::forward<FSequence>(sequence)};
   }
} _Namespace_CxIter_End



_Namespace_CxIter_Begin {
   namespace iter_detail {
      using std::begin;
      template<class FSequence>
      struct TCycledSequenceWrapper {
         struct iterator {
//            using FSequenceIt = decltype(begin(std::declval<FSequence>()));
            using FSequenceIt = _SequenceIterT<FSequence>;
            using value_xref_t = decltype(*std::declval<FSequenceIt>()); // <- normally a reference type!

            FSequenceIt p; // iterator to current element
            TCycledSequenceWrapper const *pSeqWrap;

            bool operator !=(iterator const &other) const noexcept { return this->p != other.p; }

            iterator &operator ++() noexcept { using std::begin; using std::end;
               ++ p;
               if (p == end(pSeqWrap->m_sequence))
                  p = begin(pSeqWrap->m_sequence);
               return *this;
            }

            iterator &operator --() noexcept { using std::begin; using std::end;
               if (p == begin(pSeqWrap->m_sequence))
                  p = end(pSeqWrap->m_sequence);
               -- p;
               return *this;
            }
            // ^-- both will yield undefined behavior (and likely a crash) if
            //     called on an empty sequence. However, formally we are not
            //     allowed to call ++/-- on a invalid iterator (except for end)
            //     anyway, so also without the cycle() that would be undefined...
            value_xref_t operator *() const noexcept { return *p; }

            // add default derived functions and formal iterator interface stuff
            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(value_xref_t)
         };
         FSequence m_sequence;
         iterator begin() const noexcept { using std::begin; return iterator{begin(m_sequence), this}; }
         iterator end() const noexcept { using std::end; return iterator{end(m_sequence), this}; }
         template<class _Op> void for_all(_Op op) const { for (iterator it = begin(); it != end(); ++it) { op(*it); }; }
         std::size_t constexpr size() const noexcept { return _SequenceSize(m_sequence); }
      };
   } // namespace iter_detail

   /// Return a meta-sequence which cycles through an input sequence ad inifitum
   template<class FSequence>
   auto constexpr cycle(FSequence &&sequence) -> iter_detail::TCycledSequenceWrapper<FSequence> {
      return
//          (sequence.begin() == sequence.end())?
//          throw std::invalid_argument{"cycle(seq): empty input sequence not allowed."} :
         {std::forward<FSequence>(sequence)};
   }
} _Namespace_CxIter_End



_Namespace_CxIter_Begin {
   namespace iter_detail {
      using std::begin;
      // implementation of repeat(e,n) meta-sequence with finite number of repetitions `n`
      template<class FElement, typename index_t>
      struct TRepeatElementMetaSequence {
         struct iterator {
            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(typename std::add_const<FElement>::type)  // <- FElement may be a reference type!

            index_t i; // index of element in repeat(n) sequence this iterator represents.
            pointer p;

            bool operator !=(iterator const &other) const noexcept { return this->i != other.i; }
            iterator &operator ++() noexcept { ++ i; return *this; }
            iterator &operator --() noexcept { -- i; return *this; }
            reference operator *() const noexcept { return *p; }
         };
         FElement m_element;
         index_t m_count;
         iterator begin() const noexcept { return iterator{0, &this->m_element}; }
         iterator end() const noexcept { return iterator{m_count, &this->m_element}; }
         template<class _Op> void for_all(_Op op) const { for (iterator it = begin(); it != end(); ++it) { op(*it); }; }
         std::size_t constexpr size() const noexcept { return m_count; }
      };

      // implementation of repeat(e) meta-sequence with infinite number of repetitions
      template<class FElement>
      struct TRepeatElementMetaSequence<FElement, void> {
         struct iterator {
            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(typename std::add_const<FElement>::type)
            pointer p;

            bool operator !=(iterator const &) const noexcept { return true; }

            iterator &operator ++() noexcept { return *this; }
            iterator &operator --() noexcept { return *this; }
            reference operator *() const noexcept { return *p; }
         };
         FElement m_element;
         iterator begin() const noexcept { return iterator{&this->m_element}; }
         iterator end() const noexcept { return iterator{&this->m_element}; }
         template<class _Op> void for_all(_Op op) const { for (iterator it = begin(); it != end(); ++it) { op(*it); }; }
         std::size_t constexpr size() const {
//             throw std::logic_error("taking size() of infinite sequence `repeat(e)`");
            // ^-- might still be a reasonable thing to do in some situations (e.g., like in zip(),
            //     which takes the shortest of the input sequences to define the output sequence length)
            return static_cast<std::size_t>(-1);
         }
      };
   } // namespace iter_detail

   /// Return a meta-sequence consisting of `N` repetitions of `element`
   template<class FElement>
   auto constexpr repeat(FElement &&element, unsigned long long N)
   -> iter_detail::TRepeatElementMetaSequence<FElement, unsigned long long> { return {std::forward<FElement>(element), N}; }

   /// Return a meta-sequence [e,e,e,...] infinitely repeating e := `element`
   template<class FElement>
   auto constexpr repeat(FElement &&element)
   -> iter_detail::TRepeatElementMetaSequence<FElement, void> { return {std::forward<FElement>(element)}; }

} _Namespace_CxIter_End




_Namespace_CxIter_Begin {
   namespace iter_detail {

      template<class FTrafo>
      struct TTrafoRef {
         FTrafo const *m_pTrafo;

         template<class... Args>
         auto operator()(Args&& ...args) const -> decltype((*m_pTrafo)(std::forward<Args>(args)...)) {
            return (*m_pTrafo)(std::forward<Args>(args)...);
         }
      };

      template<class FBaseIt, class FTrafo, class = void>
      struct TMappedIteratorV : private FTrafo {
         // ^-- FTrafo is used as base class to allow for C++ "empty base optimization" (EBO),
         //     see: https://en.cppreference.com/w/cpp/language/ebo
         using input_iterator_t = FBaseIt;
         using trafo_t = FTrafo;
         using this_t = TMappedIteratorV;

         FBaseIt _base_it;
         using input_type = decltype(*std::declval<FBaseIt>());
         using output_type = decltype(std::declval<FTrafo>().operator()(std::declval<input_type>()));
         trafo_t const *_trafo() const { return this; }

         output_type operator*() const { return (*_trafo())(*_base_it); }
         bool operator !=(this_t const &other) const noexcept { return this->_base_it != other._base_it; }
         this_t &operator ++() noexcept { ++_base_it; return *this; }
         this_t &operator --() noexcept { --_base_it; return *this; }

         explicit TMappedIteratorV(FBaseIt base_it, FTrafo trafo) noexcept : FTrafo(std::move(trafo)), _base_it{base_it} {}
//          explicit TMappedIteratorV(FBaseIt base_it) noexcept : _base_it{base_it} {}
         // ^-- note: this has ctors only because we use FTrafo as base for the EBO.

         // add default derived functions and formal iterator interface stuff
         using iterator = this_t;
         CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(output_type)
#ifdef INCLUDE_ABANDONED
//          // formal iterator interface stuff
// //          _CxMeta::without_ref_t<output_type> *operator->() const { return &(*_trafo())(*_base_it); }
//          // ^-- TODO: maybe not a great idea... this is okay if _trafo() function returns a sensible reference
//          //     (e.g.,if we use FTrafo = deref_f_t and *FBaseIt returns a pointer
//          //     to an object with sufficient lifetime, or it just returns a reference to a sub-object of T).
//          //     However, in general we'd probably expect _trafo(*it) to do an actual computation
//          //     and return the computed result by value, as a temporary...
//          bool operator ==(this_t const &other) const noexcept { return !this->operator !=(other); }
//
//          using iterator = TMappedIteratorV;
//          using value_type = output_type;
//          using difference_type = std::ptrdiff_t;
//          using reference = value_type&;
// //          using pointer = value_type*; // not supported in general for this type
//          using iterator_category = std::bidirectional_iterator_tag;
//          iterator operator ++(int) noexcept { iterator it{*this}; this->operator ++(); return it; }
//          iterator operator --(int) noexcept { iterator it{*this}; this->operator --(); return it; }
#endif // INCLUDE_ABANDONED
      };

      template<class FBaseIt, class FTrafo, class = void>
      struct TMappedIteratorIV : private FTrafo {
         using input_iterator_t = FBaseIt;
         using trafo_t = FTrafo;
         using this_t = TMappedIteratorIV;
         using index_t = std::size_t;

         index_t _index;
         FBaseIt _base_it;

         using input_type = decltype(*std::declval<FBaseIt>());
         using output_type = decltype(std::declval<FTrafo>().operator()(index_t(0), std::declval<input_type>()));
         trafo_t const *_trafo() const { return this; }

         output_type operator*() const { return (*_trafo())(_index, *_base_it); }
         bool operator !=(this_t const &other) const noexcept { return this->_base_it != other._base_it; }
         this_t &operator ++() noexcept { ++ _index, ++_base_it; return *this; }
         this_t &operator --() noexcept { -- _index, --_base_it; return *this; }

         explicit TMappedIteratorIV(index_t index, FBaseIt base_it, FTrafo trafo) noexcept : FTrafo(std::move(trafo)), _index(index), _base_it{base_it} {}
//          explicit TMappedIteratorIV(index_t index, FBaseIt base_it) noexcept : _index(index), _base_it{base_it} {}
         // ^-- note: this has ctors only because we use FTrafo as base for the EBO.

         // add default derived functions and formal iterator interface stuff
         using iterator = this_t;
         CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(output_type)
      };

      using std::begin;
      using std::end;
#ifdef INCLUDE_ABANDONED
//       template<class FSequence, class FTrafo, class FIter>
//       struct TMappedSequenceWrapperBase {
//          using trafo_t = FTrafo;
//          using trafo_ref_t = TTrafoRef<FTrafo>;
//          using input_type = _SequenceDerefIterT<FSequence>; // <-- typically contains REFERENCES!
// //          using value_type = decltype(std::declval<FTrafo>()(std::declval<input_type>()));
//          using value_type = decltype(*std::declval<FIter>());
//          using iterator = FIter;
//
//          FSequence m_sequence;
//          FTrafo m_trafo;
//       };
//
//       // This one keeps a copy of the input FTrafo in the sequence wrapper
//       // object, and makes iterator objects which contain a pointer (via
//       // TTrafoRef<>) to the sequence-hosted trafo.
//       template<class FSequence, class FTrafo>
//       struct TMappedSequenceWrapperV_TrafoRef : TMappedSequenceWrapperBase<
//                FSequence, FTrafo,
//                TMappedIteratorV<_SequenceIterT<FSequence>, TTrafoRef<FTrafo> > > {
//          iterator begin() const { return iterator{_SequenceBeginQ(m_sequence), trafo_ref_t{const_cast<FTrafo*>(&m_trafo)}}; }
//          iterator end() const { return iterator{_SequenceEndQ(m_sequence), trafo_ref_t{const_cast<FTrafo*>(&m_trafo)}}; }
//          std::size_t size() const { return _SequenceSizeQ(m_sequence); }
//       }
#endif // INCLUDE_ABANDONED

      // This one keeps a copy of the input FTrafo in the sequence wrapper
      // object, and makes iterator objects which contain a pointer (via
      // TTrafoRef<>) to the sequence-hosted trafo.
      template<class FSequence, class FTrafo>
      struct TMappedSequenceWrapperV_TrafoRef {
         using trafo_t = FTrafo;
         using trafo_ref_t = TTrafoRef<FTrafo>;
         using input_type = _SequenceDerefIterT<FSequence>; // <-- typically contains REFERENCES!
//          using value_type = decltype(std::declval<FTrafo>()(std::declval<input_type>()));
         using iterator = TMappedIteratorV<_SequenceIterT<FSequence>, trafo_ref_t>;
         using value_type = decltype(*std::declval<iterator>());

         FSequence m_sequence;
         FTrafo m_trafo;

         constexpr trafo_ref_t _trafo_ref() const noexcept { return trafo_ref_t{const_cast<FTrafo*>(&m_trafo)}; }
         constexpr iterator begin() const noexcept { return iterator{_SequenceBeginQ(m_sequence), _trafo_ref()}; }
         constexpr iterator end() const noexcept { return iterator{_SequenceEndQ(m_sequence), _trafo_ref()}; }
         constexpr std::size_t size() const noexcept { return _SequenceSizeQ(m_sequence); }
      };

      // This one makes one iterators which have their own FTrafo objects as
      // copies. This is a good idea if the FTrafo objects themselves are
      // small/empty (the iterators use empty-base-class-optimization), and only
      // really there because we can't make operator() a static member function.
      template<class FSequence, class FTrafo>
      struct TMappedSequenceWrapperV_TrafoCopy {
         using trafo_t = FTrafo;
         using input_type = _SequenceDerefIterT<FSequence>; // <-- typically contains REFERENCES!
//          using value_type = decltype(std::declval<FTrafo>()(std::declval<input_type>()));
         using iterator = TMappedIteratorV<_SequenceIterT<FSequence>, trafo_t>;
         using value_type = decltype(*std::declval<iterator>());

         FSequence m_sequence;
         FTrafo m_trafo;

         constexpr iterator begin() const noexcept { return iterator{_SequenceBeginQ(m_sequence), m_trafo}; }
         constexpr iterator end() const noexcept { return iterator{_SequenceEndQ(m_sequence), m_trafo}; }
         constexpr std::size_t size() const noexcept { return _SequenceSizeQ(m_sequence); }
      };

      // Choose either TMappedSequenceWrapperV_TrafoCopy or
      // TMappedSequenceWrapperV_TrafoRef depending on whether the trafo object
      // itself is of trivial size.
      template<class FSequence, class FTrafo>
      using TMappedSequenceWrapperV =
         typename std::conditional<
            (sizeof(FTrafo) <= 2*sizeof(void*)), // if doing so would cause little overhead, use _TrafoCopy
            TMappedSequenceWrapperV_TrafoCopy<FSequence,FTrafo>,
            TMappedSequenceWrapperV_TrafoRef<FSequence,FTrafo>
         >::type;


      // Mapped sequence wrapper for mapiv/mapvi: maps called indices AND elements:
      // [trafo(ie,e) for (ie,e) in enumerate(seq)]
      template<class FSequence, class FTrafo>
      struct TMappedSequenceWrapperIV {
         using trafo_t = FTrafo;
         using trafo_ref_t = TTrafoRef<FTrafo>;
         using input_type = _SequenceDerefIterT<FSequence>; // <-- typically contains REFERENCES!
//          using value_type = decltype(std::declval<FTrafo>()(0, std::declval<input_type>()));
         using iterator = TMappedIteratorIV<_SequenceIterT<FSequence>, trafo_ref_t>;
         using value_type = decltype(*std::declval<iterator>());

         FSequence m_sequence;
         FTrafo m_trafo;

         constexpr trafo_ref_t _trafo_ref() const noexcept { return trafo_ref_t{const_cast<FTrafo*>(&m_trafo)}; }
         constexpr iterator begin() const noexcept { return iterator{0, _SequenceBeginQ(m_sequence), _trafo_ref()}; }
         constexpr iterator end() const noexcept { return iterator{_SequenceSizeQ(m_sequence), _SequenceEndQ(m_sequence), _trafo_ref()}; }
         // ^-- warning: computing sequence size can be expensive for some types
         //     of sequences (e.g., std::list, or nested input sequence trafos).
         //     Do same thing as in enumerate? split into mapiv and reversible_mapiv?
         constexpr std::size_t size() const noexcept { return _SequenceSizeQ(m_sequence); }
      };
   } // namespace iter_detail

   /// `mapv(seq, trafo)` ("v": value): returns a meta-sequence corresponding to
   /// `[trafo(e) for e in seq]`; that is, which maps the original sequence
   /// elements through the function `trafo` when its iterators are dereferenced
   template<class FSequence, class FTrafo>
   auto constexpr mapv(FSequence &&sequence, FTrafo &&value_trafo_f) noexcept
   -> iter_detail::TMappedSequenceWrapperV<FSequence, FTrafo> {
      return {std::forward<FSequence>(sequence), std::forward<FTrafo>(value_trafo_f)};
   }

   /// `mapiv(seq, trafo)` ("iv": index + value): returns a meta-sequence corresponding to
   /// `[trafo(ie,e) for (ie,e) in enumerate(seq)]`; that is, which maps the original sequence
   /// elements `{seq[ie], ie = 0, …, size()-1}` through the function `trafo(ie, seq[ie])`
   /// on iterator dereferencing. Input container need not be random access.
   template<class FSequence, class FTrafo>
   auto constexpr mapiv(FSequence &&sequence, FTrafo &&value_trafo_f) noexcept
   -> iter_detail::TMappedSequenceWrapperIV<FSequence, FTrafo> {
      return {std::forward<FSequence>(sequence), std::forward<FTrafo>(value_trafo_f)};
   }


   namespace iter_detail {
      /// Output transformation which dereferences input type `T`. Note: T may be a reference type.
      template<class T>
      struct deref1_f_t {
         using result_type = decltype(*std::declval<T>());
         auto constexpr operator()(T t) const -> result_type { return *t; }
      };

      /// Output transformation which dereferences input type `T` for `N` times. Note: T may be a reference type.
      template<class T, unsigned N=1>
      struct deref_f_t {
         using result_type = decltype(deref_f_t<T, N-1>().operator()(*std::declval<T>()));
         auto constexpr operator()(T t) const -> result_type { return deref_f_t<T, N-1>().operator()(*t); }
         // ^-- hmpf. Can't make a static operator ().
      };
      template<class T> struct deref_f_t<T, 1> { auto constexpr operator()(T t) const -> decltype(*t) { return *t; } };
      template<class T> struct deref_f_t<T, 0> { auto constexpr operator()(T t) const -> T { return t; } };
   }

   /// deref(seq) returns a meta-sequence which is equivalent to seq, except
   /// that dereferencing its iterators returns operator* applied to the
   /// original seq elements (`[*e for e in seq]`), rather than just the original
   /// elements (`[e for e in seq]`) themselves.
   ///
   /// This can be useful for handling sequences of pointers, smart-pointers, or
   /// otherwise wrapped objects.
   template<class FSequence>
   auto constexpr deref(FSequence &&sequence) noexcept
   -> iter_detail::TMappedSequenceWrapperV_TrafoCopy<FSequence, iter_detail::deref1_f_t<_SequenceDerefIterT<FSequence> > > {
      return {std::forward<FSequence>(sequence), iter_detail::deref1_f_t<_SequenceDerefIterT<FSequence> >()};
   }

   template<class FBaseIt, unsigned N>
   using deref_iterator_t = iter_detail::TMappedIteratorV<FBaseIt, iter_detail::deref_f_t<decltype(*std::declval<FBaseIt>()),N> >;
#ifdef INCLUDE_ABANDONED
   // ^-- that works, but maybe making an actual class might somewhat reduce the 10012323-lines-long-type-names syndrom...
   // UPDATE: hmpf.. need to do that. Can't just derive from class, because otherwise the
   // `iterator`-valued return values of some functions (e.g., operator ++) will only
   // refer to the TMappedIteratorV base class...
//    template<class FBaseIt, unsigned N>
//    struct deref_iterator_t : public iter_detail::TMappedIteratorV<FBaseIt, iter_detail::deref_f_t<decltype(*std::declval<FBaseIt>()),N> > {
//       using base_t = iter_detail::TMappedIteratorV<FBaseIt, iter_detail::deref_f_t<decltype(*std::declval<FBaseIt>()),N> >;
//       explicit deref_iterator_t(FBaseIt base_it) : base_t{base_it} {}
//    };
#endif // INCLUDE_ABANDONED
} _Namespace_CxIter_End



#ifdef INCLUDE_OPTIONALS
// // this one more or less works. Didn't implement keys yet, though. And it makes two sequences.
// // Not sure if this is better or worse than the std::list version.
// _Namespace_CxIter_Begin {
//    namespace iter_detail {
//    template<class T> T const &_ElementItselfCref(T const &v) { return v; }
//
//    template<class T, class FKeyFn>
//    struct TCompareViaKey {
//       FKeyFn m_KeyFn;
//       bool constexpr operator()(T const &a, T const &b) const { return m_KeyFn(a) < m_KeyFn(b); }
//    };
//    template<class T, class FKeyFn>
//    auto key_compare_f(FKeyFn key) -> TCompareViaKey<T, FKeyFn> { return {key}; }
//
//
//    namespace iter_detail {
//       template<class FSequence> struct TSortedSequenceWrapper {
//          using value_type = decltype(*std::declval<FSequence>().begin());
//          // ^-- note that this value_type will typically contain REFERENCES!
//          //     (either on the entire type (e.g., retval of std::vector<T>::begin()),
//          //     or to some subject (e.g., reval of cx::enumerate(seq)::begin()).
//          //     It may contain concrete values of FSequence is a inline-generator
//          //     sequence (e.g., cx::iter::numbers()).
//          using stored_value_t = FValueOrRef<value_type>;
//          using output_sequence_t = typename std::vector<stored_value_t>;
//
//          FSequence m_sequence;
//          output_sequence_t m_out;
//
//          TSortedSequenceWrapper(FSequence &&seq) :
//             m_sequence{std::forward<FSequence>(seq)},
//             m_out{m_sequence.begin(), m_sequence.end()}
//          {
//             std::stable_sort(m_out.begin(), m_out.end());
//          }
//
//          using iterator = deref_iterator_t<typename output_sequence_t::iterator, 1>;
//
//          iterator begin() { return iterator{_SequenceBeginQ(m_out)}; }
//          iterator end() { return iterator{_SequenceEndQ(m_out)}; }
//          std::size_t size() const { return _SequenceSizeQ(m_out); }
//       };
//    } // namespace iter_detail
//
//
//    template<class FSequence>
//    auto sorted(FSequence &&sequence) -> typename iter_detail::TSortedSequenceWrapper<FSequence> {
//       return iter_detail::TSortedSequenceWrapper<FSequence>{std::forward<FSequence>(sequence)};
//    }
// } _Namespace_CxIter_End
#endif // INCLUDE_OPTIONALS


_Namespace_CxIter_Begin {
   template<class T> T const &_ValueItself(T const &v) { return v; }
   // ^-- used as default sort key. Probably needs a better name...

   template<class T, class FKeyFn>
   struct TKeyCompare {
      FKeyFn m_KeyFn;
      bool constexpr operator()(T const &a, T const &b) const { return m_KeyFn(a) < m_KeyFn(b); }
   };
   template<class T, class FKeyFn>
   auto key_compare_f(FKeyFn key) -> TKeyCompare<T, FKeyFn> { return {key}; }

   namespace iter_detail {
      using std::begin;

      template<class FSequence> struct TSortedSequenceHelper {
         using value_type = decltype(*begin(std::declval<FSequence>())); // <-- typically contains REFERENCES!
         using stored_type = FValueOrRef<value_type>;
         using output_sequence_t = std::list<stored_type>;
         // ^-- why std::list?
         //     - list<T>.sort() requires neither that T is copyable nor movable
         //       (because the list sort implementation can just move the node
         //       links!). This makes this construction more widely applicable.
         //     - it does not require us to know how many output elements are
         //       there. Therefore no requirement on .size() of the input
         //       sequence. For std::vector (or the like this) would be required
         //       to prevent (possibly large) reallocation/move operations.
         //     - unlike std::sort(beg,end) (on a [beg,end) range given by
         //       random access iterators), list<T>::sort automatically performs
         //       a stable sort.

         using input_sequence_t = _CxMeta::without_ref_t<FSequence>;

         static output_sequence_t _MakeList(input_sequence_t &&seq) {
            using std::begin; using std::end;
            output_sequence_t vl;
            for (auto &&e : seq)
               vl.push_back(std::move(e));
            return vl;
         }

         static output_sequence_t _MakeList(input_sequence_t &seq) {
            using std::begin; using std::end;
            output_sequence_t vl{begin(seq), end(seq)};
            return vl;
         }

         static output_sequence_t sorted(FSequence &&seq) {
            output_sequence_t vl = _MakeList(seq); vl.sort(); return vl;
         }
            // ^-- TODO: change this to allow moving (instead of copying) the elements of seq in
            //           case the actual object behind FSequence is it is an xvalue. (note that
            //           FSequence will be a reference unless sorted(seq) was called on a
            //           temporary/xvalue seq)

         template<class FSortKey>
         static output_sequence_t sorted(FSequence &&seq, FSortKey &&key) {
            output_sequence_t vl = _MakeList(seq);
            // We have FValueOrRef<T> types stored as actual values in the container.
            // Translate original sort key function, presumably specified in terms
            // of value_types (more accurately, cx::without_cvref_t<value_type>),
            // into a sort key function for the wrapped values.
            auto meta_key = [&](stored_type const &sv){
               return key(*sv);
            };
            vl.sort(key_compare_f<stored_type>(meta_key));
            return vl;
         }
      };
   } // namespace iter_detail


   template<class FSequence>
   auto sorted(FSequence &&sequence) -> decltype(deref(typename iter_detail::TSortedSequenceHelper<FSequence>::output_sequence_t{})) {
      return deref(iter_detail::TSortedSequenceHelper<FSequence>::sorted(std::forward<FSequence>(sequence)));
   }

   template<class FSequence, class FSortKeyFn>
   auto sorted(FSequence &&sequence, FSortKeyFn &&key)
   -> decltype(deref(typename iter_detail::TSortedSequenceHelper<FSequence>::output_sequence_t{})) {
      return deref(
         iter_detail::TSortedSequenceHelper<FSequence>::sorted(
            std::forward<FSequence>(sequence), std::forward<FSortKeyFn>(key)
         )
      );
   }

} _Namespace_CxIter_End




_Namespace_CxIter_Begin {
   namespace iter_detail {
      using std::begin;
      template<class _Dummy, class... FSequences> struct TZippedSequenceWrapper;

      template<class... FSequences, unsigned... Is>
      struct TZippedSequenceWrapper<_CxMeta::index_list_t<Is...>, FSequences...> {
         struct iterator {
            // TODO: try it with decltype_packet_t? could reduce template bloat
            //       if the zipped sequence types are all equal.
            // using FSequenceIts = std::tuple<decltype(begin(std::declval<FSequences>()))...>;
            // using output_type = decltype(std::tie(*begin(std::declval<FSequences>())...));
            // ^-- note the "decltype"! This yields whatever type *it returns (normally a reference!)
            using FSequenceIts = std::tuple<_SequenceIterT<FSequences>...>;
            using output_type = decltype(std::tie(*std::declval<_SequenceIterT<FSequences>>()...));

            FSequenceIts p; // actual iterators to elements

            // the zip iterator == operator returns true if *any* of the iterator pairs
            // agree. This should lead to the zip iteration terminating as soon as
            // any of the input sequences hits its end (comparing equal to it == seq.end()).
            bool operator !=(iterator const &other) const noexcept {
               using std::get; return _CxMeta::all_pp((get<Is>(this->p) != get<Is>(other.p))...);
            }
            iterator &operator ++() noexcept { using std::get; [](...){}((++get<Is>(p), 0)...); return *this; }
            iterator &operator --() noexcept { using std::get; [](...){}((--get<Is>(p), 0)...); return *this; }
            // ^-- this one has the order of calling ++/-- on the sub-sequences undefined, if I am not mistaken
            //     (note: the [](...){} is a inline-lambda expression, with vararg parameters ((...)), which does nothing ({}))

            output_type operator *() const noexcept { using std::get; return std::tie(*get<Is>(p)...); }

            // add default derived functions and formal iterator interface stuff
            CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(output_type)
#ifdef INCLUDE_ABANDONED
//             using output_type = decltype(std::tie(*std::declval<FSequences>().begin()...));
//             iterator &operator ++() noexcept { using std::get; static_cast<void>(((++ get<Is>(p), 0))...); return *this; }
//             iterator &operator --() noexcept { using std::get; static_cast<void>(((-- get<Is>(p), 0))...); return *this; }
// ^-- cgk: I don't understand why that does not work. Shouldn't I be able to make a free-standing expression with
//     the comma operator? g++ complains about some missing binary operator(?!).
//             iterator &operator ++() noexcept { using std::get; int _dummy[] = {(++get<Is>(p), 0)...}; (void)_dummy; return *this; }
//             iterator &operator --() noexcept { using std::get; int _dummy[] = {(--get<Is>(p), 0)...}; (void)_dummy; return *this; }
            // ^-- this one has the order of calling ++/-- on the sub-sequences well-defined

//             value_type *operator->() noexcept { return &this->operator()(); }
//             // these to make std::list(beg,end) c'tor happy...
//             using difference_type = std::ptrdiff_t;
//             using reference = value_type&;
//             using pointer = value_type*;
//             using iterator_category = std::bidirectional_iterator_tag;
//             iterator operator ++(int) noexcept { iterator it{*this}; this->operator ++(); return it; }
//             iterator operator --(int) noexcept { iterator it{*this}; this->operator --(); return it; }
//             bool operator ==(iterator const &other) const noexcept { return !this->operator !=(other); }
#endif // INCLUDE_ABANDONED
         };
         std::tuple<FSequences...> m_sequences;
         iterator begin() const noexcept { using std::begin; using std::get; return iterator{{begin(get<Is>(m_sequences))...}}; }
         iterator end() const noexcept { using std::end; using std::get;
            assert(sizeof...(Is) == 0 ||
                   _CxMeta::all_pp((_SequenceSizeQ(get<Is>(m_sequences)) == _SequenceSizeQ(get<0>(m_sequences)))...)
            );
            return iterator{{end(get<Is>(m_sequences))...}};
         }
         // ^--- WARNING: if combined with reversed() or other sequence transforms which actually
         //      use the end iterators, then this ONLY is okay if all input sequences have the same length!
         //      Otherwise reversed(zip(...)), for example, will start each of the sub-sequences at their
         //      respective end, NOT at the end of the zipped sequence. There is, unfortunately, no
         //      simple way to fix that, as general sequences would not allow a random access iterator
         //      propagation to the true end...
         template<class _Op> void for_all(_Op op) const {
            for (iterator it = begin(); it != end(); ++it) {
               using std::get; op(*get<Is>(it.p)...);
            };
         }
         std::size_t constexpr size() const noexcept { using std::get; return _CxMeta::min_pp(_SequenceSizeQ(get<Is>(m_sequences))...); }
         // ^-- needed for reversed() sequence transform.
      };
   } // namespace iter_detail

   /// zip(A,B,C,...) returns a meta-sequence over tuples with matching items
   /// from A, B, C, ...:
   ///
   ///   zip(A,B,...) ≍ [tuple(A[i],B[i],...) for i in range(min(len(A),len(B),...)].
   ///
   /// WARNING:
   /// - if reversed() is meant to be used with zip(), then all input sequences
   ///   must have the same length to yield correct results!
   /// - Otherwise zip(A,B,C,...) will terminate on the shortest input sequence.
   template<class... FSequences>
   auto constexpr zip(FSequences&&... sequences) noexcept
   -> iter_detail::TZippedSequenceWrapper<_CxMeta::index_list_of_size_t<sizeof...(FSequences)>, FSequences...> {
      return {{std::forward<FSequences>(sequences)...}};
   }
} _Namespace_CxIter_End


#ifdef INCLUDE_OPTIONALS
// TODO: probably get rid of this branch. I think the simple struct version is
//       the better option, in the end. If necessary, I could add the tuple stuff
//       to it, too.
#if (CX_ENUMERATE_IAV >= 1)
_Namespace_CxIter_Begin { namespace iter_detail {
   template<class FIndex, class FValue> struct TIndexAndValue;
} } _Namespace_CxIter_End

template<class I, class V> struct std::tuple_size<_CxIter::iter_detail::TIndexAndValue<I,V> >{ enum { value = 2 }; };
template<class I, class V> struct std::tuple_element<0, _CxIter::iter_detail::TIndexAndValue<I,V> >{ typedef I type; };
template<class I, class V> struct std::tuple_element<1, _CxIter::iter_detail::TIndexAndValue<I,V> >{ typedef V type; };


_Namespace_CxIter_Begin {
   namespace iter_detail {

      namespace detail {
         template<std::size_t iElemT, class FIndex, class FValue> struct _TIndexAndValueGetImpl;
      }
      // Type of the actual object's you'll get as variables in range-based for loops
      // with the enumerate() below. E.g., in loops such as
      //
      //   for (auto &&it : enumerate(my_vector)) { .. }
      //   for (auto const &it : enumerate(my_vector)) { .. }
      //
      // the base type of `it` will be one of those.
      //
      // Note: this auxiliary class is always instanciated with *reference types* for
      // FIndex and FValue! The referenced index remains in the parent iterator
      // object, and the value in the enumerated parent sequence. `i` and `v` here are
      // not copies.
      template<class FIndex, class FValue>
      struct TIndexAndValue {
         typedef FIndex index_type;
         typedef FValue value_type;
         index_type i;
         value_type v;

         index_type const &index() const { return i; }
         value_type &value() { return v; }
         value_type const &value() const { return v; }

         // Add some iterator-like dereferencing operators to get to the base value.
         // May look a bit odd at first, but I don't think it's so bad (compared with
         // the alternatives, specifically)
         typedef decltype(&v) pointer_type; // <-- can't just do value_type *, becaue value_type is instanciated as a reference type.
         value_type &operator*() { return v; }
         value_type const &operator*() const { return v; }
         pointer_type operator->() { return &v; }
         pointer_type const operator->() const { return &v; }

         template<std::size_t iElemT>
         auto get() -> typename std::tuple_element<iElemT, TIndexAndValue>::type {
            return detail::_TIndexAndValueGetImpl<iElemT, FIndex, FValue>::get(this);
         }
         template<std::size_t iElemT>
         auto get() const -> typename std::tuple_element<iElemT, TIndexAndValue>::type const {
            return detail::_TIndexAndValueGetImpl<iElemT, FIndex, FValue>::get_const(this);
         }
      };

      namespace detail {
         template<class I, class V> struct _TIndexAndValueGetImpl<0,I,V> {
            static I       &get(TIndexAndValue<I,V> *iv)             { return iv->i; }
            static I const &get_const(TIndexAndValue<I,V> const *iv) { return iv->i; }
         };
         template<class I, class V> struct _TIndexAndValueGetImpl<1,I,V> {
            static V const &get_const(TIndexAndValue<I,V> const *iv) { return iv->v; }
            static V       &get(TIndexAndValue<I,V> *iv)             { return iv->v; }
         };
      }

   } // namespace iter_detail

   // iav: index and value
   template<typename index_t, typename value_t>
   using iav_t = _CxIter::iter_detail::TIndexAndValue<index_t, value_t>;
} _Namespace_CxIter_End
#define CX_ENUMERATE_IAV_DEFINED
#endif // #if (CX_ENUMERATE_IAV >= 1)
#endif // INCLUDE_OPTIONALS


#ifndef CX_ENUMERATE_IAV_DEFINED
_Namespace_CxIter_Begin {
   /// iav = index and value, a possible meta-type to use for enumerate().
   /// Unpacks as
   /// `for(auto [i,v] : enumerate(seq)) {...}`,
   /// and uses (i,v) as default compare key (e.g., for sorted())
   template<typename index_t, typename value_t>
   struct basic_iav_t { //
      index_t i; value_t v;
      bool constexpr operator < (basic_iav_t const &other) const { return std::tie(this->i, this->v) < std::tie(other.i, other.v); }
   };

   /// vai = value and index. Still unpacks as
   /// `for(auto [i,v] : enumerate(seq)) {...}`,
   /// but uses (v,i) as default compare key (e.g., for sorted())
   template<typename index_t, typename value_t>
   struct basic_vai_t {
      index_t i; value_t v;
      bool constexpr operator < (basic_vai_t const &other) const { return std::tie(this->v, this->i) < std::tie(other.v, other.i); }
   };

   enum {
      // avoid clash with METASEQ_*. Both used in enumerate<_Flags>(seq).
      IAV_Mask = 0xf000,
      IAV_OrderKey_VI = 0x1000
   };
   // A somewhat more generic variant of basic_vai_t / basic_iav_t, to generate
   // meta-classes for the return types of enumerate(), which can be controlled
   // by flags in some respects
   template<unsigned _Flags>
   struct iav {
      template<typename index_t, typename value_t>
      struct type {
         index_t i; value_t v;
         // do lex sort by default. This is for sorted() etc.
         bool constexpr operator < (type const &other) const {
            return (_FlagOffQ(_Flags, IAV_OrderKey_VI)?
                        (std::tie(this->i, this->v) < std::tie(other.i, other.v)) :
                        (std::tie(this->v, this->i) < std::tie(other.v, other.i))
            );
         }
      };
   };

} _Namespace_CxIter_End
#endif


_Namespace_CxIter_Begin {
   namespace iter_detail {
      // Next up: sequence wrapper representing the meta-sequence returned by
      // enumerate():
      //
      // Note on how this works:
      // - enumerate(T &&) just contains a std::forward<T>() to construct a
      //   TIndexedSequenceWrapper<T>
      // - with this, if enumerate(T &&) is called on an lvalue, the FSequence
      //   type *here* will be deduced as a reference type (either T& or T const
      //   &). So the member variable FSequence m_sequence just contains a
      //   reference to the existing object.
      // - however, if enumerate(T &&) is called on an rvalue (originally either
      //   prvalue or xvalue), we here arrive at a non-reference FSequence type,
      //   and then m_sequence becomes an actual container object. To which we
      //   pass a rvalue-reference in the aggregate initialization in
      //   enumerate() (i.e., with whatever enumerate was called on converted
      //   into an xvalue). For this reason, the implicit construction
      //   TIndexedSequenceWrapper<T>(T&&) will engage the move constructor, not
      //   the copy constructor.
      //
      // ...so, at least in theory, in neither case the input sequence is
      // actually copied---only either referenced (enumerate(<lvalue>)) or moved
      // (enumerate(<rvalue>)).
      template<class FBaseIt, class FIndex, class FOutputType>
      struct TIndexingIterator {
         using input_iterator_t = FBaseIt;
         using this_t = TIndexingIterator;
         using index_type = FIndex;
         using input_type = decltype(*std::declval<FBaseIt>());
         using output_type = FOutputType;

         index_type       i; // current element index relative to sequence.begin()
         input_iterator_t p; // actual iterator to element

         bool operator !=(this_t const &other) const noexcept { return this->p != other.p; }
         this_t &operator ++() noexcept { ++ i; ++ p; return *this; }
         this_t &operator --() noexcept { -- i; -- p; return *this; }

         output_type operator *() const noexcept { return output_type{i, *p}; }

         // add default derived functions and formal iterator interface stuff
         using iterator = this_t;
         CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(output_type)

         constexpr difference_type operator - (iterator const &b) const { return this->i - b.i; };
      };

      using std::begin;
      using std::end;


      template<class FSequence, flagfield_t _Flags, template<typename I, typename V> class _TIndexAndValue>
      struct TIndexedSequenceWrapper {
         // FBaseIt is effectively `decltype(begin(std::declval<FSeq>()));` ...
         // but we can't use that here because it would refer to `begin(...)`,
         // and later defining our own begin() apparently would retroactively
         // change the meaning of `begin` here, and that is an error. Says g++.
         // Hooray for C++...
         using FBaseIt = _SequenceIterT<FSequence>;
//          using FBaseIt = decltype(begin(std::declval<FSequence>()));
         using index_type = std::size_t;
         using input_type = decltype(*std::declval<FBaseIt>());
         using iterator = TIndexingIterator<FBaseIt, index_type, _TIndexAndValue<index_type, input_type> >;
#ifdef INCLUDE_ABANDONED
//          struct iterator {
//             using FBaseIt = decltype(begin(std::declval<FSequence>()));
//             using index_type = std::size_t;
//             // note: input_type is defined as the decltype of the expression of
//             // whatever *seq.begin() of the original sequence returns, *without*
//             // reduction of reference or cv character. That means that in most
//             // cases the value_type will be a *reference*! That includes iteration
//             // over standard containers (e.g., std::vector<>) as well as over
//             // raw arrays. It may not be a reference if the sequence we iterate
//             // over is not in fact a container, but something which generates
//             // and returns items by value.
//             using input_type = decltype(*std::declval<FBaseIt>());
//
//             index_type  i; // current element index relative to sequence.begin()
//             FBaseIt p; // actual iterator to element
//
//             bool operator !=(iterator const &other) const noexcept { return this->p != other.p; }
//             iterator &operator ++() noexcept { ++ i; ++ p; return *this; }
//             iterator &operator --() noexcept { -- i; -- p; return *this; }
//
//             using output_type = _TIndexAndValue<index_type, input_type>;
//             output_type operator *() const noexcept { return output_type{i, *p}; }
//
//             // add default derived functions and formal iterator interface stuff
//             CX_ADD_DEFAULT_BIDI_ITER_MEMBERS(output_type)
// #ifdef INCLUDE_ABANDONED
// //             // these to make std::list(beg,end) c'tor happy...
// //             bool operator ==(iterator const &other) const noexcept { return this->p == other.p; }
// //             iterator operator ++(int) noexcept { iterator it{*this}; this->operator ++(); return it; }
// //             iterator operator --(int) noexcept { iterator it{*this}; this->operator --(); return it; }
// //             using difference_type = std::ptrdiff_t;
// // //             using value_type = value_type;
// //             using reference = value_type&;
// //             using pointer = value_type*;
// //             using iterator_category = std::bidirectional_iterator_tag;
// #endif // INCLUDE_ABANDONED
//          };
#endif // INCLUDE_ABANDONED
         FSequence m_sequence;
         std::size_t constexpr size() const noexcept { return _SequenceSizeQ(m_sequence); }
         iterator constexpr begin() const noexcept { using std::begin; return iterator{0, begin(m_sequence)}; }
//          iterator constexpr end() const noexcept { using std::end; return {_CxMeta::sequence_size(m_sequence), end(m_sequence)}; }
         // ^-- hmpf. That is expensive for some container types (e.g., std::list), but without it
         //     reverse() and backward iteration can't work. Also, it requires a .size() (or std::size
         //     specialization) to be actually present, which otherwise we would not need, and which
         //     in some cases (e.g., generator specializations) is not necessarily trivial to make.
#ifdef INCLUDE_ABANDONED
//          iterator constexpr begin() const noexcept { return iterator{0, _SequenceBeginQ(m_sequence)}; }
//          iterator constexpr end() const noexcept { using std::end; return {0, end(m_sequence)}; }
//          iterator constexpr end() const noexcept { using std::end;
//             return iterator{(_FlagOnQ(_Flags, METASEQ_Reversible)?
//                                  _CxMeta::sequence_size(m_sequence) :
//                                  0
//                             ),
//                             end(m_sequence)
//             };
//          }
// ^-- hmpf... this requires instanciating .size(), regardless of which side of the
//     constexpr-conditional it ends up at. So this won't compile on
//     generators/meta-sequences which don't have .size(), even if we use straight
//     enumerate() in non-reversible mode, where .size() is not actually used.
//     Would require `if constexpr` to fix, but that is only available in ≥C++17.
#endif // INCLUDE_ABANDONED
#if __cplusplus >= 201703L
         iterator constexpr end() const noexcept { using std::end;
            if constexpr (_FlagOnQ(_Flags, METASEQ_Reversible))
               return iterator{_SequenceSizeQ(m_sequence), end(m_sequence)};
            else
               return iterator{0, end(m_sequence)};
         }
#else
         struct _ReversibleOff {
            template<class FThis> static iterator constexpr end(FThis *pThis) noexcept {
               using std::end; return iterator{0, end(pThis->m_sequence)};
            }
         };
         struct _ReversibleOn {
            template<class FThis> static iterator constexpr end(FThis *pThis) noexcept {
               using std::end; return iterator{_SequenceSizeQ(pThis->m_sequence), end(pThis->m_sequence)};
            }
         };

         iterator constexpr end() const noexcept {
            return _CxMeta::conditional_t<_FlagOnQ(_Flags, METASEQ_Reversible), _ReversibleOn, _ReversibleOff>::end(this);
         }
#endif
      };
   } // namespace iter_detail

   /// Returns a meta-sequence wrapper which adds to each element of the original
   /// sequence a running index, starting at 0, just as python's `enumerate(seq)`.
   /// Concretely: enumerate(seq): for each e in seq, the meta sequence
   /// yields (ie,e), where
   ///
   /// - ie = 0 for e = *seq.begin()
   /// - ie = 1 for e = *(++iterator(begin))
   /// - ie = 2 for e = *(++(++iterator(begin())))
   ///
   /// Comments:
   /// - The input sequence does not need to have natural indices or a []
   ///   operator---the indices are kept track of as the iterators as progressed
   ///   (e.g., it will work fine for a std::list or std::set)
   ///
   /// - This version is NOT reversible (won't work with reversed()).
   ///   Use reversible_enumerate(seq) instead to get a enumeration meta-sequence
   ///   which can be used with reversed(seq).
   ///
   ///   Background:
   ///   - making a reversible meta-sequences would require enumerate() to call
   ///     `.size()` on the input sequence (to construct the `end()` iterator).
   ///   - Depending on the type of input sequence, this
   ///     could incur a non-negligible overhead (e.g., for std::lists, std::sets,
   ///     results of combinatorial meta-sequences (e.g., combinations(seq,K),
   ///     permutations(seq), groupby(seq,key), ...).
   ///   - For this reason, we disable this by default and instead provide an
   ///     alternative implementation (reversible_enumerate) which performs the
   ///     additional work.
   ///
   /// Efficiency:
   /// - No space overhead
   /// - Effectively no runtime overhead (compared to iterating over the
   ///   original sequence and keeping track of the indices yourself).
   /// Notes input sequence:
   /// - Will work on anything which has std::begin() and std::begin()
   ///   defined, and these functions returning something which is at least a
   ///   ForwardIterator
   ///   (https://en.cppreference.com/w/cpp/named_req/ForwardIterator).
   /// - This includes all std containers and user types which have .begin() and
   ///   .end() members, as well as raw C arrays, and any generator objects which
   ///   are *not* containers (e.g., std::vector<bool>, meta-sequences in this
   ///   file, or explicit sequences generators like ray_grid).
   /// - If the original sequence's iterators fulfill BidrectionalIterator, the
   ///   returned iterators of the meta-sequence will also be bidirectional.
   template<class FSequence>
   auto constexpr enumerate(FSequence &&sequence) noexcept
   -> iter_detail::TIndexedSequenceWrapper<FSequence, 0, basic_vai_t> {
//    -> iter_detail::TIndexedSequenceWrapper<FSequence, 0, iav<0>::template type> {
      return {std::forward<FSequence>(sequence)};
   }

   /// As enumerate(seq), but returns a meta-sequence which can be subjected to
   /// reversed().
   template<class FSequence>
   auto constexpr reversible_enumerate(FSequence &&sequence) noexcept
   -> iter_detail::TIndexedSequenceWrapper<FSequence, METASEQ_Reversible, basic_vai_t> {
//    -> iter_detail::TIndexedSequenceWrapper<FSequence, METASEQ_Reversible, iav<0>::template type> {
      return {std::forward<FSequence>(sequence)};
   }

   /// As enumerate(seq), but allows customizing the returned type for
   /// the indices and values. This is specified in terms of a class template of the form
   /// `template<typename I, typename V> struct iav_t<I,V>{...}`.
   /// This construction can be used to define non-trivial transformations on
   /// the input sequence, to define custom ordering operators (operator <), or
   /// similar. Examples:
   /// ```
   ///     #include <iostream>
   ///     #include <vector>
   ///     #include <cmath>
   ///     #include "CxIterTools.h"
   ///
   ///     // make a basic index_and_value struct with just two data members;
   ///     // additionally, add a non-standard `operator <` to get sorted(...)
   ///     // to sort by key (index,value) in reverse.
   ///     template<typename index_t, typename value_t>
   ///     struct my_iav_t {
   ///        index_t my_index; value_t my_value;
   ///
   ///        bool operator < (my_iav_t const &other) const {
   ///           return std::tie(other.my_index, other.my_value) < std::tie(this->my_index, this->my_value);
   ///        }
   ///     };
   ///
   ///     // enumerate<iav_t> will be instanciate the class as iav_t<I,V>{i,v}.
   ///     // However, what you do with it is up to you. This class template
   ///     // computes powers v^i instead of storing indices i and values v.
   ///     template<typename index_t, typename value_t>
   ///     struct my_pow_trafo_t {
   ///        double m_value;
   ///        my_pow_trafo_t(index_t i, value_t v) : m_value{std::pow((double)v,i)} {}
   ///        operator double() const { return m_value; }
   ///     };
   ///
   ///     namespace it = cx::iter;
   ///     int main() {
   ///        std::vector<int> seq{3,5,2,4,12,1};
   ///        std::cout << "it::sorted(it::enumerate(seq)):\n";
   ///        for (auto e : it::sorted(it::enumerate(seq))) {
   ///           std::cout << "  seq[" << e.i << "] = " << e.v << std::endl;
   ///        }
   ///        std::cout << "it::enumerate<my_iav_t>(seq):\n";
   ///        for (auto e : it::enumerate<my_iav_t>(seq)) {
   ///           std::cout << "  seq[" << e.my_index << "] = " << e.my_value << std::endl;
   ///        }
   ///        std::cout << "it::sorted(it::enumerate<my_iav_t>(seq)):\n";
   ///        for (auto e : it::sorted(it::enumerate<my_iav_t>(seq))) {
   ///           std::cout << "  seq[" << e.my_index << "] = " << e.my_value << std::endl;
   ///        }
   ///        std::cout << "it::enumerate<my_pow_trafo_t>(seq):\n";
   ///        for (auto e : it::enumerate<my_pow_trafo_t>(seq)) {
   ///           std::cout << "  " << e << std::endl;
   ///        }
   ///     }
   /// ```
   /// Possible output:
   /// ```
   ///     it::sorted(it::enumerate(seq)):
   ///       seq[5] = 1
   ///       seq[2] = 2
   ///       seq[0] = 3
   ///       seq[3] = 4
   ///       seq[1] = 5
   ///       seq[4] = 12
   ///     it::enumerate<my_iav_t>(seq):
   ///       seq[0] = 3
   ///       seq[1] = 5
   ///       seq[2] = 2
   ///       seq[3] = 4
   ///       seq[4] = 12
   ///       seq[5] = 1
   ///     it::sorted(it::enumerate<my_iav_t>(seq)):
   ///       seq[5] = 1
   ///       seq[4] = 12
   ///       seq[3] = 4
   ///       seq[2] = 2
   ///       seq[1] = 5
   ///       seq[0] = 3
   ///     it::enumerate<my_pow_trafo_t>(seq):
   ///       1
   ///       5
   ///       4
   ///       64
   ///       20736
   ///       1
   /// ```
   template<template<typename I, typename V> class iav_t, class FSequence>
   auto constexpr enumerate(FSequence &&sequence) noexcept
   -> iter_detail::TIndexedSequenceWrapper<FSequence, 0, iav_t> {
      return {std::forward<FSequence>(sequence)};
   }

   /// Convenience function for some sub-functionality of enumerate<iav_t>:
   /// - `enumerate<IAV_OrderKey_VI>(seq)` generates a meta-sequence in which
   ///   the returned index-and-value pairs have a operator < which compares
   ///   lexicographically by (v,i) instead of the default (i,v).
   /// - `enumerate<IAV_OrderKey_VI | METASEQ_Reversible>(seq)` additionally
   ///   makes the returned sequence reversible (i.e., allows using `reversed()`
   ///   on it).
   template<unsigned _Flags, class FSequence>
   auto constexpr enumerate(FSequence &&sequence) noexcept
   -> iter_detail::TIndexedSequenceWrapper<FSequence, (_Flags & METASEQ_Mask), iav<(_Flags & IAV_Mask)>::template type> {
      return {std::forward<FSequence>(sequence)};
   }


#ifdef INCLUDE_ABANDONED
   // ^-- note: base of enumerate() implementation is recycled from here:
   // https://www.reedbeta.com/blog/python-like-enumerate-in-cpp17/
   // I made several adjustments, though (and I don't claim they are necessarily for the better),
   // in particular to allow it to run already in C++11-mode.
   //
   // See ~/dev/cx/tests/enumerate/enum_test_cx_include_version.cpp for tests.
   // Looked like all the core things work out (no copy of container unless needed,
   // and if done, it's using move, the elements do not appear to be copied in any
   // variant I tested, and it works in both C++11 and C++17 now (structured
   // bindings only in the latter of course)). Still might need some more in-depth
   // examination before I'd swear on it (references to temporaries etc---not
   // always easy to find, although an initial sanitizing run didn't find anything)

#if 0
   // The base version. Core is recycled from here:
   // https://www.reedbeta.com/blog/python-like-enumerate-in-cpp17/
   // I made several adjustments, but mostly cosmetical, and I don't claim they are necessarily for the better.
   //
   // This works fine as-is, in principle. The only thing irritating is that it
   // returns a std::tuple (via tie), which is rather ugly because there is no
   // sensible way to access its elements (the only way to get them is
   // std::get<n>(..)). With structured binding that is a non-issue, but I do not
   // wish to enforce C++17 support for the time being. (Some of my software should
   // run on HPC clusters, which for some reason often have 10 year old compilers)
   template<class FSequence, class FSequenceIt = decltype(std::begin(std::declval<FSequence>()))>
   constexpr auto enumerate(FSequence &&sequence)
   {
      struct iterator {
         std::size_t
            i; // element index relative to sequence.begin()
         FSequenceIt
            p; // actual iterator to element
         bool operator != (iterator const &other) const { return this->p != other.p; }
         void operator ++ () { ++ i; ++ p; }
         auto operator * () const { return std::tie(i, *p); }
      };
      struct FSequenceWrapper {
         FSequence m_sequence;
         auto begin() { return iterator{0, std::begin(m_sequence)}; }
         auto end() { return iterator{0, std::end(m_sequence)}; }
      };
      return FSequenceWrapper{std::forward<FSequence>(sequence)};
   }
#endif
#endif // INCLUDE_ABANDONED
} _Namespace_CxIter_End

/*
/// Defines a minimal iterator interface to allow use in range-based for loops
/// and generic container printing mechanism. This one is for objects which have
/// a working [] operator to access elements, but not necessarily much else.
/// Examples are raw-pointer based arrays (with non-unit stride, otherwise one
/// can just use the pointers directly).
/// Usage: Add:
///
///     CX_IMPLEMENT_ITERATOR_IndexInBracket(TypeOfClassHere,const_iterator,const)
///     CX_IMPLEMENT_ITERATOR_IndexInBracket(TypeOfClassHere,iterator,)
///
/// to class declaration to make both const and non-const iterators which wrap
/// calls to operator [].
#define CX_IMPLEMENT_ITERATOR_IndexInBracket(HostType,IteratorType,ConstOrNothing) \
   struct IteratorType { \
      HostType ConstOrNothing \
         *m_pArrayObj; \
      size_t \
         m_Index; \
      IteratorType &operator ++() { ++m_Index; return *this; } \
      IteratorType &operator --() { --m_Index; return *this; } \
      bool operator != (IteratorType const& other) const { \
         return this->m_pArrayObj != other.m_pArrayObj || this->m_Index != other.m_Index; \
      } \
      bool operator == (IteratorType const& other) const { \
         return this->m_pArrayObj == other.m_pArrayObj || this->m_Index != other.m_Index; \
      } \
      auto operator *() -> decltype((*m_pArrayObj)[m_Index]) { return (*m_pArrayObj)[m_Index]; } \
   }; \
   IteratorType begin() ConstOrNothing { return IteratorType{this, 0}; } \
   IteratorType end() ConstOrNothing { return IteratorType{this, size()}; }
   // ^--- note: == operator not strictly required.
//       typename std::decay<decltype(std::declval<HostType>()[0])>::type
//       ConstOrNothing &operator *() { return (*m_pArrayObj)[m_Index]; }
^-- moved to CxDefs.h for the moment.
*/


#ifdef INCLUDE_ABANDONED
   // RANT: ...seriously what were the C++ standards guys thinking when they designed this??!
   //
   // - No way to access parameter packs by index, neither types nor values
   //   (it can be done by meta-programming hacks like here, but do we really want that?)
   //
   //   - No way to create a correspondence to parameter packs inside a function.
   //     They indeed can *only* be made or used with actual parameters.
   //     So just about *every single function* we might be dealing with needs
   //     to be split into one function to generate an index list for a parameter pack,
   //     and another functions which receives it as argument, for the simple reason
   //     that there is no other way to access them.
   //
   //   - In C++17 there are fold expressions... but only for parameter packs (e.g.,
   //     not any of the other things implementing get<...>), and only based on
   //     a very small number of predefined arithmetic operators (not generic unary
   //     or binary functions)... WHY?
   //
   // - The way tuples work...
   //   - instead of specifying a straight-forward compiler-level implementation
   //     (which they needed ANYWAY, for the parameter packs! Because tuples
   //     are exactly what those are), the entire thing is meant to be based on some
   //     insanity template meta-programmng mess.
   //
   //   - And the syntax is just stupid. Admittedly, my >= C++11 experience is still
   //     limited, but in my trials so far, these things have been mostly cumbersome
   //     (not the least because of all the forwarding/rvalue ref stuff).
   //     In most cases simply *not* using tuples had been the better option!
   //
   //   - e.g., why is there no operator []? There are const-based overloads,
   //     why not constexpr based ones, too? instead, it's creating an own local
   //     namespace, `using std::get` inside this namespace (because you can't
   //     *just* use std::get if you want to be compatible, because other `get`
   //     methods need to be resolved via ADL), then `get<...>`(t) to access
   //     elements). Was there really *no way at all* to add an operator []?
   //     Yes, different tuple elements may have different types, but so have
   //     the expressions get<n>(T). I cannot believe that this couldn't easily
   //     be fixed with a bit of compiler magic (and tuples really *SHOULD*
   //     be implemented in the compiler).
   //
   //   - Tuples are super easy to use unsafely, including when using them for
   //     their intended core usage scenarios, and when following standard
   //     recommended usage patterns to the letter. I already managed to create
   //     several situations in trial programs in which even with all compiler
   //     warnings and memory sanitizing etc enabled, I clearly could access
   //     variables beyond their end of lifetime (admittedly, I explicitly
   //     *made* the programs to check for situations in which this would
   //     arise).
   //
   // - basic aggregates can be used in aggregate initialization ({}) and
   //   structured binding, including simple structs like `{int a; int b;}`.
   //   Very nice---in principle. But to make this practically usable, it is
   //   clear that the designers of the language must have recognized that in
   //   many situations:
   //
   //   - structs have a well-defined number and order of arguments
   //
   //   - and the users of the language can recognize their meaning even without
   //     element names (just like they can do so for function arguments...)
   //
   //   So far so good. So... why then is there no way to access these elements in
   //   a generic way by index in *any other* situation than initialization or
   //   structured binding?! Why is there no std::get<n> for aggregates?
#endif // INCLUDE_ABANDONED

#undef _CxIter

#endif // CX_ITER_TOOLS_H
